server:
  port: 8088
  servlet:
    context-path: /jarvis/boot
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jarvis-samples-spring-boot
  mvc:
    # get param
    format:
      date: yyyy-MM-dd

jarvis:
  oss:
    enabled: true
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: yoga-jarvis
    access-key-id: LTAI5tFj2U4DVcsjFqgXqTXB
    access-key-secret: y3RkH2NX5cwj6KODD6X86qLzV6Ul1X
  id:
    worker-id: 1
    data-center-id: 1
