server:
  port: 8088
  servlet:
    context-path: /jarvis/boot
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jarvis-samples-spring-boot
  mvc:
    # get param
    format:
      date: yyyy-MM-dd

jarvis:
  oss:
    enabled: true
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: yoga-jarvis
    access-key-id: LTAI5tFj2U4DVcsjFqgXqTXB
    access-key-secret: y3RkH2NX5cwj6KODD6X86qLzV6Ul1X
  id:
    worker-id: 1
    data-center-id: 1

http:
  client:
    # 保存在客户端
    rsa-pri-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAK3e+hO7dhreTSbNveGK6dAgz4WGyImhkeU/2YfSH0N602d7tRO/M40ATTO+6Kh0BiP2wd8/NqODkTcJy1zIfxq2X6t6ghqt4Y/Nast8MTkCTFBc60uHYahtI+AFIU62rpSa5OYcDsICGt4a/LZVpphg/Y0vvV6dB34tyzqWWpDhAgMBAAECgYBPef4r6OO6smTn2OHz5/Cqv2S8r3iZWO58sSv5JrY9vTZHNkf2R88Do+CmR5zH64knBVNnfdi285v8YZDAz7ExPq54gV94leDP5eaxtFRePOAYWsCy0ZwgDhgUWv7oIXT3rH/lSAKEcv3ZkSFgbPjtbQjuEEfNLzphHflYzQfq5QJBANqSYLjinshS2dmFytZYUK+n4JzZzN6HGF65hTcnsB6E3j1yhUN+CPWmCVMkyIyfB91IfZKDIYC/Z1YQbxf6SMsCQQDLpQg9Jkp3UOk4WR+OmBn814Lx591GDNs4rBVe//nxjIPobWGJ+SvsLVnlNOIIOJqs7ZkETAJx3oxgJ+pU2NODAkBpmVTvnlWWdSjZRiGkg1CgPRxwy22GiYCFq14oMp2NcSYqS90EqazMeeaBbAEUp3TWPUKl+YLDQDY9x3zU+dAXAkEAkLB9HhVqq0PNsL+B8GqZbFAjNYUsbm0MBUQfGxR8nebcgfPVbZagYnoGeRgN0RGGtH9MTQVEZ2tcCaXSlN5JyQJBAJP+X6wL+5GmXOGsWzV0Ykg7Fs2iBPw7ZejtbGUnnbvKS2oyJESgkYqHz1TNyYQ/5sYIyzgwMHGckoyBpNjUkKM=
    # 保存在服务端
    rsa-pub-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCt3voTu3Ya3k0mzb3hiunQIM+FhsiJoZHlP9mH0h9DetNne7UTvzONAE0zvuiodAYj9sHfPzajg5E3CctcyH8atl+reoIareGPzWrLfDE5AkxQXOtLh2GobSPgBSFOtq6UmuTmHA7CAhreGvy2VaaYYP2NL71enQd+Lcs6llqQ4QIDAQAB
    # 保存在客户端
    aes-key: tql7VVeMSvNQtqbj
    aes-iv: Fwo8YfJL4Bmt3Egf
  server:
    # 保存在服务端
    rsa-pri-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJRMhQ+rJkZ0s05p6xl4e2TOf8wkDK/4ANFcehwg3EZqvuXZQIhJzTvUanil+IVifxay/6/jYAIAFb3fqJL0RB1sdygQY9dgSdwCQvCnaTFFkAW8WoVO8wQSXbUtrMjIwRUgViZdfgsCY5orHLACilq8FlpZP5ExoI+ZDdLnLOOZAgMBAAECgYAZI9eyzkrQytvSwTXvvXL9pdwYWUwlUJ+i3lB9ED0HWvU9tdSwxgIa0Gm0Rj6ZLhdpW7LouF0AOc91vsKvFuWs7IR3EO1z9MAlt0Xyp0Gp6rmdBtSO2fGd5tFbj+OYE86sowjDjbl9OJlomDs350iHzd80zyWlAeCMLTwez4m4WQJBAOEMVrpR8jS+Ompg4UFWwK7geZ7Qyq1WhNNb3cpyWuQkgFe2R8OSTwY2TO2oCPCsBBdqEK3Ljh3160SHkWjdTxsCQQCose+U6tdXDAMfJizF3+dujo50mfVJEm5egAMjpqL/DADnpzrCW+21VJWZ59xsmV7t4M77/6UTQxarzUVrIJ9bAkABX6Hn4TgpOkABBjZZv73NU3Fqlrul8zE8WQMxiSEk41QlNOebOflhgFNX3/6t+V7NBci0RtnHNQkKkglBKpihAkBg7ZxTXHxOr8A7bZvcNkKr640+wheF3Ok9syAao+yTzznV4OiKNHfo8KjkvayRWa6Jz9oeQU2AO9QS8ucoHp5xAkEAtJZN3zFUD1Pt86zGQUqQBMj4aJkpSM2kKF3QdDsuLj5n4Zx5j/AQPee22DGPQQWdnhyOKQ4uF5vIwUctnZF6Uw==
    # 保存在客户端
    rsa-pub-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUTIUPqyZGdLNOaesZeHtkzn/MJAyv+ADRXHocINxGar7l2UCISc071Gp4pfiFYn8Wsv+v42ACABW936iS9EQdbHcoEGPXYEncAkLwp2kxRZAFvFqFTvMEEl21LazIyMEVIFYmXX4LAmOaKxywAopavBZaWT+RMaCPmQ3S5yzjmQIDAQAB