server:
  port: 10001
  servlet:
    context-path: /jarvis/admin
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jarvis-admin

log:
   path: D:\Users\yoga\Settings\Projects\Logs\${spring.application.name}
   name: all
