server:
  port: 10001
  servlet:
    context-path: /jarvis/admin
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: jarvis-admin
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 600MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jarvis?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
  thymeleaf:
    # thymeleaf 页面的缓存开关，默认 true 开启缓存
    # 建议在开发阶段关闭 thymeleaf 页面缓存，目的实时看到页面
    cache: false

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #驼峰下划线转换
      #column-underline: true
      #数据库大写转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  config: classpath:logback-spring.xml

log:
   path: D:\Users\yoga\Settings\Projects\Logs\${spring.application.name}
   name: all

user:
  login:
    salt: oi3b2dt5