server:
  port: 8090
  servlet:
    context-path: /jarvis/shop
spring:
  application:
    name: jarvis-ddd-shop
  profiles:
    active: dev
log:
  path: /Users/yoga/logs/${spring.application.name}
  name: app